version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - 'npm install --global sfdx-cli'
      - 'wget https://dlcdn.apache.org//ant/binaries/apache-ant-1.10.13-bin.tar.gz'
      - 'tar -xzf apache-ant-1.10.13-bin.tar.gz'
      - 'export ANT_HOME=$PWD/apache-ant-1.10.13'
      - 'export PATH=$PATH:$ANT_HOME/bin'
      - 'wget https://ap16.salesforce.com/dwnld/SfdcAnt/salesforce_ant_52.0.zip'
      - 'unzip salesforce_ant_52.0.zip'
      - 'cp ant-salesforce.jar $ANT_HOME/lib/'
  build:
    commands:
      - 'ant build/build.xml'
#   post_build:
#     commands:
#       - echo Build completed on `date`
# cache:
#   paths:
#     - '/root/.npm/*/'
#     - '/usr/local/lib/node_modules/*/'